[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

[params.modules.utils]
  filter = "[^0-9A-Za-zŽžÀ-ÿ ;.,\\/'’\"]-"
  raw = false