baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-utils'

[module]
  replacements = 'github.com/gethinode/mod-utils -> ../..'
  [[module.imports]]
    path = "github.com/gethinode/mod-utils"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"